"""Added Index to ensure template sequence names are unique within a workspace

Revision ID: 6e9874de3204
Revises: faa1e883e333
Create Date: 2026-05-26 14:21:28.760685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9874de3204'
down_revision: Union[str, Sequence[str], None] = 'faa1e883e333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_input_entity_template_sequence_workspace_name',
        'input_entity',
        ['workspace_id', sa.literal_column('lower(name)')],
        unique=True,
        postgresql_where=sa.text("type = 'template_sequence'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_input_entity_template_sequence_workspace_name',
        table_name='input_entity',
        postgresql_where=sa.text("type = 'template_sequence'"),
    )
    # ### end Alembic commands ###
