"""make UIDs unique

Revision ID: 8deebdee4ca0
Revises: 995b57893b33
Create Date: 2026-06-05 08:37:44.311580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8deebdee4ca0'
down_revision: Union[str, Sequence[str], None] = '995b57893b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_line_workspace_uid'), 'line', type_='unique')
    op.create_index('uq_line_workspace_uid_ci', 'line', ['workspace_id', sa.literal_column('lower(uid)')], unique=True)
    op.drop_constraint(op.f('uq_primer_workspace_uid'), 'primer', type_='unique')
    op.create_index(
        'uq_primer_workspace_uid_ci', 'primer', ['workspace_id', sa.literal_column('lower(uid)')], unique=True
    )
    op.drop_constraint(op.f('uq_sequence_sample_workspace_uid'), 'sequence_sample', type_='unique')
    op.create_index(
        'uq_sequence_sample_workspace_uid_ci',
        'sequence_sample',
        ['workspace_id', sa.literal_column('lower(uid)')],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sequence_sample_workspace_uid_ci', table_name='sequence_sample')
    op.create_unique_constraint(
        op.f('uq_sequence_sample_workspace_uid'),
        'sequence_sample',
        ['workspace_id', 'uid'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index('uq_primer_workspace_uid_ci', table_name='primer')
    op.create_unique_constraint(
        op.f('uq_primer_workspace_uid'), 'primer', ['workspace_id', 'uid'], postgresql_nulls_not_distinct=False
    )
    op.drop_index('uq_line_workspace_uid_ci', table_name='line')
    op.create_unique_constraint(
        op.f('uq_line_workspace_uid'), 'line', ['workspace_id', 'uid'], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
