"""switch from S3 storage to db storage

Revision ID: 995b57893b33
Revises: 6e9874de3204
Create Date: 2026-06-02 10:42:03.851886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995b57893b33'
down_revision: Union[str, Sequence[str], None] = '6e9874de3204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_whitelist',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.CheckConstraint("email <> ''", name='email_whitelist_email_not_empty'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email', name='uq_email_whitelist_email'),
    )
    op.add_column('sequence', sa.Column('file_content', sa.Text(), nullable=False))
    op.drop_column('sequence', 'file_path')
    op.add_column('sequencing_file', sa.Column('file_content', sa.LargeBinary(), nullable=False))
    op.drop_column('sequencing_file', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_file', sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sequencing_file', 'file_content')
    op.add_column('sequence', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sequence', 'file_content')
    op.drop_table('email_whitelist')
    # ### end Alembic commands ###
