"""switch to OICD for user auth

Revision ID: dff59c137a7e
Revises: 8deebdee4ca0
Create Date: 2026-09-23 16:28:13.701973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff59c137a7e'
down_revision: Union[str, Sequence[str], None] = '8deebdee4ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('user', sa.Column('external_subject', sa.String(), nullable=True))
    op.alter_column('user', 'email', existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint('uq_user_auth_identity', 'user', ['auth_provider', 'external_subject'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_auth_identity', 'user', type_='unique')
    op.alter_column('user', 'email', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column('user', 'external_subject')
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###
