"""enforce workspace copies with composite foreign keys

Revision ID: e5067e8acca3
Revises: eae106d3b1d2
Create Date: 2026-10-09 17:43:10.832392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5067e8acca3'
down_revision: Union[str, Sequence[str], None] = 'eae106d3b1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_input_entity_id_workspace', 'input_entity', ['id', 'workspace_id'])
    op.drop_constraint(op.f('primer_workspace_id_fkey'), 'primer', type_='foreignkey')
    op.create_foreign_key(
        'fk_primer_workspace_matches_input_entity',
        'primer',
        'input_entity',
        ['id', 'workspace_id'],
        ['id', 'workspace_id'],
    )
    # Added as nullable, backfilled from the workspace of each instance's sequence, then made NOT NULL
    op.add_column('sequence_instance', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE sequence_instance
        SET workspace_id = input_entity.workspace_id
        FROM input_entity
        WHERE input_entity.id = sequence_instance.sequence_id
        """
    )
    op.alter_column('sequence_instance', 'workspace_id', nullable=False)
    op.create_unique_constraint('uq_sequence_instance_id_workspace', 'sequence_instance', ['id', 'workspace_id'])
    op.create_foreign_key(
        'fk_sequence_instance_workspace_matches_sequence',
        'sequence_instance',
        'input_entity',
        ['sequence_id', 'workspace_id'],
        ['id', 'workspace_id'],
    )
    op.drop_constraint(op.f('sequence_sample_workspace_id_fkey'), 'sequence_sample', type_='foreignkey')
    op.create_foreign_key(
        'fk_sequence_sample_workspace_matches_instance',
        'sequence_sample',
        'sequence_instance',
        ['id', 'workspace_id'],
        ['id', 'workspace_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sequence_sample_workspace_matches_instance', 'sequence_sample', type_='foreignkey')
    op.create_foreign_key(
        op.f('sequence_sample_workspace_id_fkey'), 'sequence_sample', 'workspace', ['workspace_id'], ['id']
    )
    op.drop_constraint('fk_sequence_instance_workspace_matches_sequence', 'sequence_instance', type_='foreignkey')
    op.drop_constraint('uq_sequence_instance_id_workspace', 'sequence_instance', type_='unique')
    op.drop_column('sequence_instance', 'workspace_id')
    op.drop_constraint('fk_primer_workspace_matches_input_entity', 'primer', type_='foreignkey')
    op.create_foreign_key(op.f('primer_workspace_id_fkey'), 'primer', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint('uq_input_entity_id_workspace', 'input_entity', type_='unique')
    # ### end Alembic commands ###
