"""drop email whitelist

Revision ID: eae106d3b1d2
Revises: dff59c137a7e
Create Date: 2026-09-24 17:19:43.596241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'eae106d3b1d2'
down_revision: Union[str, Sequence[str], None] = 'dff59c137a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_whitelist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_whitelist',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.CheckConstraint("email::text <> ''::text", name=op.f('email_whitelist_email_not_empty')),
        sa.PrimaryKeyConstraint('id', name=op.f('email_whitelist_pkey')),
        sa.UniqueConstraint(
            'email', name=op.f('uq_email_whitelist_email'), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    # ### end Alembic commands ###
