"""initial schema

Revision ID: faa1e883e333
Revises:
Create Date: 2026-05-26 14:19:55.634670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa1e883e333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('is_instance_admin', sa.Boolean(), nullable=False),
        sa.CheckConstraint('char_length(display_name) >= 4', name='user_display_name_min_length'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'workspace',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'input_entity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'line',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'uid', name='uq_line_workspace_uid'),
    )
    op.create_table(
        'tag',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.CheckConstraint("name <> ''", name='tag_name_not_empty'),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'name', name='uq_tag_workspace_name'),
    )
    op.create_table(
        'workspace_membership',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='workspacerole'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'workspace_id', name='uq_workspace_membership_user_workspace'),
    )
    op.create_table(
        'base_sequence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'sequence_type',
            sa.Enum(
                'locus', 'allele', 'plasmid', 'pcr_product', 'restriction_fragment', 'linear_dna', name='sequencetype'
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['id'],
            ['input_entity.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'input_entity_tag',
        sa.Column('input_entity_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['input_entity_id'],
            ['input_entity.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tag.id'],
        ),
        sa.PrimaryKeyConstraint('input_entity_id', 'tag_id'),
    )
    op.create_table(
        'line_parent',
        sa.Column('line_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.CheckConstraint('line_id <> parent_id', name='line_not_own_parent'),
        sa.ForeignKeyConstraint(
            ['line_id'],
            ['line.id'],
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['line.id'],
        ),
        sa.PrimaryKeyConstraint('line_id', 'parent_id'),
    )
    op.create_table(
        'line_tag',
        sa.Column('line_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['line_id'],
            ['line.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tag.id'],
        ),
        sa.PrimaryKeyConstraint('line_id', 'tag_id'),
    )
    op.create_table(
        'primer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(), nullable=True),
        sa.Column('sequence', sa.String(), nullable=False),
        sa.CheckConstraint("uid IS NULL OR uid <> ''", name='primer_uid_not_empty'),
        sa.ForeignKeyConstraint(
            ['id'],
            ['input_entity.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'uid', name='uq_primer_workspace_uid'),
    )
    op.create_table(
        'sequence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('overhang_crick_3prime', sa.Integer(), nullable=False),
        sa.Column('overhang_watson_3prime', sa.Integer(), nullable=False),
        sa.Column('seguid', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['base_sequence.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sequence_instance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sequence_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['sequence_id'],
            ['base_sequence.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'template_sequence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['base_sequence.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sequence_in_line',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('line_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['sequence_instance.id'],
        ),
        sa.ForeignKeyConstraint(
            ['line_id'],
            ['line.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sequence_sample',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['sequence_instance.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workspace_id'],
            ['workspace.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'uid', name='uq_sequence_sample_workspace_uid'),
    )
    op.create_table(
        'sequencing_file',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sequence_id', sa.Integer(), nullable=False),
        sa.Column('original_name', sa.String(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['sequence_id'],
            ['sequence.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sequence_id', 'original_name', name='uq_sequencefile_sequenceid_originalname'),
    )
    op.create_table(
        'source',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'Source',
                'DatabaseSource',
                'CollectionSource',
                'ManuallyTypedSource',
                'UploadedFileSource',
                'RepositoryIdSource',
                'SequenceCutSource',
                'AssemblySource',
                'OligoHybridizationSource',
                'PolymeraseExtensionSource',
                'AnnotationSource',
                'ReverseComplementSource',
                'PCRSource',
                'LigationSource',
                'HomologousRecombinationSource',
                'GibsonAssemblySource',
                'InFusionSource',
                'OverlapExtensionPCRLigationSource',
                'InVivoAssemblySource',
                'RestrictionAndLigationSource',
                'GatewaySource',
                'CreLoxRecombinationSource',
                'RecombinaseSource',
                'CRISPRSource',
                'RestrictionEnzymeDigestionSource',
                'AddgeneIdSource',
                'WekWikGeneIdSource',
                'SEVASource',
                'BenchlingUrlSource',
                'SnapGenePlasmidSource',
                'EuroscarfSource',
                'IGEMSource',
                'OpenDNACollectionsSource',
                'NCBISequenceSource',
                'GenomeCoordinatesSource',
                name='sourcetype',
            ),
            nullable=False,
        ),
        sa.Column('extra_fields', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['sequence.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'source_input',
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('input_entity_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('sequence_instance_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['input_entity_id'],
            ['input_entity.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sequence_instance_id'],
            ['sequence_instance.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source.id'],
        ),
        sa.PrimaryKeyConstraint('source_id', 'position'),
    )
    op.create_table(
        'assembly_fragment',
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('left_location', sa.String(), nullable=True),
        sa.Column('right_location', sa.String(), nullable=True),
        sa.Column('reverse_complemented', sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            'left_location IS NOT NULL OR right_location IS NOT NULL', name='assembly_fragment_has_location'
        ),
        sa.ForeignKeyConstraint(
            ['source_id', 'position'],
            ['source_input.source_id', 'source_input.position'],
        ),
        sa.PrimaryKeyConstraint('source_id', 'position'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assembly_fragment')
    op.drop_table('source_input')
    op.drop_table('source')
    op.drop_table('sequencing_file')
    op.drop_table('sequence_sample')
    op.drop_table('sequence_in_line')
    op.drop_table('template_sequence')
    op.drop_table('sequence_instance')
    op.drop_table('sequence')
    op.drop_table('primer')
    op.drop_table('line_tag')
    op.drop_table('line_parent')
    op.drop_table('input_entity_tag')
    op.drop_table('base_sequence')
    op.drop_table('workspace_membership')
    op.drop_table('tag')
    op.drop_table('line')
    op.drop_table('input_entity')
    op.drop_table('workspace')
    op.drop_table('user')
    # ### end Alembic commands ###
